# Generated by Django 4.2.3 on 2023-08-07 16:29

import FishingPortal.business.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50), FishingPortal.business.validators.ValidateIsAlAlphaNumHypAndUnderscore()])),
                ('place', models.CharField(validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50)])),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='business.business')),
                ('participants', models.ManyToManyField(blank=True, related_name='competitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
