# Generated by Django 4.2.3 on 2023-08-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='active',
            new_name='is_active',
        ),
    ]
