# Generated by Django 4.2.3 on 2023-08-04 05:16

import FishingPortal.auth_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50), FishingPortal.auth_app.validators.ValidateIsOnlyAlpha()]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50), FishingPortal.auth_app.validators.ValidateIsOnlyAlpha()]),
        ),
    ]
