# Generated by Django 4.2.3 on 2023-08-03 16:49

import FishingPortal.business.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=250, validators=[FishingPortal.business.validators.ValidateIsAlAlphaNumHypAndUnderscore(), django.core.validators.MinLengthValidator(2)])),
            ],
        ),
    ]
