# Generated by Django 4.2.3 on 2023-08-10 07:55

import FishingPortal.auth_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_picture_description_picture_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='title',
            field=models.CharField(default=1, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MinLengthValidator(20), FishingPortal.auth_app.validators.ValidateIsOnlyAlpha()]),
            preserve_default=False,
        ),
    ]
